image: docker:latest
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay
  GOPATH: $CI_PROJECT_DIR/../gopath

stages:
  - build
  - push

before_script:
  - docker info
  - mkdir -p $GOPATH
  - apk update
  - apk add git go-tools make lftp
  - go env

.build_template: &build_definition
  script:
    - make pull
    - go get -d ./...
    - go get -d github.com/elgatito/cross-compiler
    - go tool vet -unsafeptr=false .
    - make libs
    - make $PLATFORM
  except:
    - tags
    - master

.push_template: &push_definition
  script:
    - make pull
    - go get -d ./...
    - go get -d github.com/elgatito/cross-compiler
    - go tool vet -unsafeptr=false .
    - make libs
    - make $PLATFORM
  after_script:
    - |
        mkdir -p build
        lftp -c "open 'ftp://$FTP_USER:$FTP_PASS@$FTP_HOST'; \
        mkdir -p -f elementum-binaries/$CI_BUILD_REF_NAME; \
        lcd build; \
        cd elementum-binaries/$CI_BUILD_REF_NAME; \
        mirror --reverse --verbose --include-glob *; \
        exit;"
  only:
    - tags
    - master

android-arm:
  stage: build
  variables:
    PLATFORM: android-arm
  <<: *build_definition
android-arm-bin:
  stage: push
  variables:
    PLATFORM: android-arm
  <<: *push_definition

android-x64:
  stage: build
  variables:
    PLATFORM: android-x64
  <<: *build_definition
android-x64-bin:
  stage: push
  variables:
    PLATFORM: android-x64
  <<: *push_definition

android-x86:
  stage: build
  variables:
    PLATFORM: android-x86
  <<: *build_definition
android-x86-bin:
  stage: push
  variables:
    PLATFORM: android-x86
  <<: *push_definition

darwin-x64:
  stage: build
  variables:
    PLATFORM: darwin-x64
  <<: *build_definition
darwin-x64-bin:
  stage: push
  variables:
    PLATFORM: darwin-x64
  <<: *push_definition

linux-arm:
  stage: build
  variables:
    PLATFORM: linux-arm
  <<: *build_definition
linux-arm-bin:
  stage: push
  variables:
    PLATFORM: linux-arm
  <<: *push_definition

linux-armv7:
  stage: build
  variables:
    PLATFORM: linux-armv7
  <<: *build_definition
android-armv7-bin:
  stage: push
  variables:
    PLATFORM: linux-armv7
  <<: *push_definition

linux-arm64:
  stage: build
  variables:
    PLATFORM: linux-arm64
  <<: *build_definition
linux-arm64-bin:
  stage: push
  variables:
    PLATFORM: linux-arm64
  <<: *push_definition

linux-x64:
  stage: build
  variables:
    PLATFORM: linux-x64
  <<: *build_definition
linux-x64-bin:
  stage: push
  variables:
    PLATFORM: linux-x64
  <<: *push_definition

linux-x86:
  stage: build
  variables:
    PLATFORM: linux-x86
  <<: *build_definition
linux-x86-bin:
  stage: push
  variables:
    PLATFORM: linux-x86
  <<: *push_definition

windows-x64:
  stage: build
  variables:
    PLATFORM: windows-x64
  <<: *build_definition
windows-x64-bin:
  stage: push
  variables:
    PLATFORM: windows-x64
  <<: *push_definition

windows-x86:
  stage: build
  variables:
    PLATFORM: windows-x86
  <<: *build_definition
windows-x86-bin:
  stage: push
  variables:
    PLATFORM: windows-x86
  <<: *push_definition
